custom:
  web-socket:
    sub-prefix: /api/sub
    pub-prefix: /api/pub
    end-point: /api/ws-chat
    chat:
      message-path: /chat/message
      room-path: /chat/rooms
      summary-event-path: /chat/summary

