spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_server?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-total: 5
      test-on-borrow: true
      test-on-return: true
      test-on-create: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0


auth:
  server:
    url: http://localhost:9090
  key:
    public-path: classpath:rsa/login_public_key.pem

file:
  upload:
    profile-dir: C:\project_file\live_chat\src\main\resources\image\profile
    chat-image-dir: C:\project_file\live_chat\src\main\resources\image\chat
    chat-file-dir: C:\project_file\live_chat\src\main\resources\image\file
#    profile-dir: ${CHAT_UPLOAD_ROOT}/image/profile
#    chat-image-dir: ${CHAT_UPLOAD_ROOT}/image/chat
#    chat-file-dir: ${CHAT_UPLOAD_ROOT}/image/file
    chat-file-max-size: 5MB
    chat-file-allowed-extensions:
      - pdf
      - txt
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - zip
      - hwp
      - hwpx
      - jpg
      - jpeg
      - png

logging:
  file:
    name: ./logs/chat-server.log
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 7
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # 파일용 시간 포맷
  level:
    com.chat_server: info
    org.springframework.security: warn
    org.hibernate.SQL: warn
    io.netty: warn
    reactor.netty: warn
    org.apache.http: info
    org.springframework: debug
    sun.rmi: info
    javax.management: info
    org.springframework.messaging: warn
    org.springframework.web.socket.messaging: warn
    org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler: warn
    org.springframework.messaging.handler.annotation.support: warn
    org.springframework.messaging.converter: warn
    org.springframework.messaging.support.ExecutorSubscribableChannel: warn