spring:
  data:
    redis:
      database: 0

auth:
  server:
    url: ${AUTH_SERVER_URL:auth-server:9090}
  key:
    public-path: ${AUTH_KEY_PUBLIC_PATH:classpath:rsa/login_public_key.pem}

file:
  upload:
    profile-dir: /app/uploads/profile
    chat-image-dir: /app/uploads/chat/images
    chat-file-dir: /app/uploads/chat/files
    chat-file-max-size: 1MB
    chat-file-allowed-extensions:
      - pdf
      - txt
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - zip
      - hwp
      - hwpx
      - jpg
      - jpeg
      - png
logging:
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 7
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.chat_server: info
    org.springframework.security: warn
    org.hibernate.SQL: warn
    io.netty: warn
    reactor.netty: warn
    org.apache.http: info
    org.springframework: debug
    sun.rmi: info
    javax.management: info
    org.springframework.messaging: warn
    org.springframework.web.socket.messaging: warn
    org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler: warn
    org.springframework.messaging.handler.annotation.support: warn
    org.springframework.messaging.converter: warn
    org.springframework.messaging.support.ExecutorSubscribableChannel: warn