spring:
  application:
    name: chat_server
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  jackson:
    time-zone: Asia/Seoul
  profiles:
    group:
      dev:
        - custom
        - web
      prod:
        - custom
        - web

server:
  port: 7070
  tomcat:
    uri-encoding: UTF-8

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: debug