spring:
  application:
    name: chat_server
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 추 후에 환경 파일로 따로 빼야함
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/chat_server?serverTimezone=UTC&characterEncoding=UTF-8
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-total: 5
      test-on-borrow: true
      test-on-return: true
      test-on-create: true
  profiles:
    active: dev,custom
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: info
    com.chat_server: debug
    org.springframework: info
    org.springframework.web.filter: info
    org.hibernate.SQL: info
    # SQL 로그 보기 (선택)
    io.netty: info
    reactor.netty: info
    org.apache.http: info
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
server:
  port: 7070
  tomcat:
    uri-encoding: UTF-8
custom:
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    cache-timeout: 10


# 추후 config 서버로 별도로 뺄 예정
auth:
  api:
    address: /api/v1/auth
  key:
    public-key-path: classpath:rsa/login_public_key.pem
