spring:
  data:
    redis:
      database: 0

auth:
  server:
    url: ${AUTH_SERVER_URL:auth-server:9090}
  key:
    public-path: ${AUTH_KEY_PUBLIC_PATH:classpath:rsa/login_public_key.pem}

logging:
  level:
    com.chat_server: info
    org.springframework.security: info
    org.hibernate.SQL: info