custom:
  auth:
    header:
      token-expiration: X-Token-Expires-In
  error:
    messages:
      TOKEN_EXPIRED: "Access Token이 만료되었습니다."
      INVALID_TOKEN: "유효하지 않은 토큰입니다."
      NO_PERMISSION: "접근 권한이 없습니다."
  api:
    prefix: "/api/v1"