custom:
  auth:
    header:
      token-expiration: X-Token-Expires-In
  error:
    messages:
      TOKEN_EXPIRED: "Access Token이 만료되었습니다."
      INVALID_TOKEN: "유효하지 않은 토큰입니다."
      NO_PERMISSION: "접근 권한이 없습니다."
      NOT_DEFINE: "정의되지 않은 오류 입니다."
  api:
    common:
      prefix: "/api/v1"
    user:
      prefix: "/users"

    friend:
      prefix: "/friends"
    search:
      prefix: "/search"

