spring:
  data:
    redis:
      database: 0

auth:
  server:
    url: ${AUTH_SERVER_URL:auth-server:9090}
  key:
    public-path: ${AUTH_KEY_PUBLIC_PATH:classpath:rsa/login_public_key.pem}

file:
  upload:
    profile-dir: /app/uploads/profile
    chat-image-dir: /app/uploads/chat/images
    chat-file-dir: /app/uploads/chat/files
    chat-file-max-size: 1MB
    chat-file-allowed-extensions:
      - pdf
      - txt
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - zip
      - hwp
      - hwpx
      - jpg
      - jpeg
      - png
logging:
  level:
    com.chat_server: info
    org.springframework.security: info
    org.hibernate.SQL: info