spring:
  application:
    name: chat_server
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/chat_server?serverTimezone=UTC&characterEncoding=UTF-8
    dbcp2:
      max-idle: 5
      min-idle: 5
      max-total: 5
      test-on-borrow: true
      initial-size: 5

